---
title: "02_clean_data"
output: html_document
date: "2026-02-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

02 - clean data
- Convert -9999 values to NA
- Filter low coverage days
*Done BEFORE converting to daily data*

Convert -9999 values to NA

```{r}
flux_vars <- c("GPP", "Qle", "Tair", "SW_rad", "Rn", "Precip", "Pa", "VPD")

#Clean dataframe, convert to 'na' if '-9999'

df_2 <- df_1 %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999)
  )) %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999.9)
  ))
```


Filter low coverage days:
- Removes days that don't have enough half-hourly measurements
- Assumes half-hourly data
- Leaves only days with >90% data coverage
```{r}
filter_low_coverage_days <- function(df, min_frac = 0.9, steps_per_day = 48) {

  min_steps <- ceiling(min_frac * steps_per_day)

  df %>%
    group_by(date = floor_date(date, "day")) %>%
    mutate(n_steps = n()) %>%
    ungroup() %>%
    filter(n_steps >= min_steps) %>%
    select(-n_steps)
}

df_clean <- filter_low_coverage_days(df_2)
```


