---
title: "04_growing_season"
output: html_document
date: "2026-02-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

04 - growing season filter
1. Growing season
2. Drop NAs before fitting model

```{r}

6. Growing season filter
Currently:
- Shortwave radiation threshold
- GPP > 0 threshold

```{r}
filter_gs <- function(df, rad_thresh = 100) {
  df %>%
    filter(SW_rad > rad_thresh, GPP > 0)
}

#Apply to dataset

growing_season_data <- filter_gs(df)
```

7. Drop NA values

```{r}
df_monthly <- monthly %>%
  drop_na(GPP, VPD, Tair, Precip, Pa, Qle)

```


Notes:

Growing season:
- Currently a bit too harsh
- Assumes that photosynthesis responds rapidly instantly to radiation
 - growing season is defined purely by light
 
 Ideas:
 - PFT-specific thresholds?
 Would require having a column in each site specifying its PFT
 - Soft GPP threshold instead of GPP > 0 - percentile or 0.5
 - Add temperature, growing season often light and thermal limited
 - Rolling window - sustained activity. When mean GPP over ~7 days is positive?
 - Radiation percentile instead of absolute threshold which may be wrong for some sites/seasons, adapts across sites
 - Soil moisture/precipitation?
 - **Top 3 months of highest GPP during the year**
```


