---
title: "explore_ozflux_03"
output: html_document
date: "2026-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Monday 2nd Feb:

- Add vcmax and LLC to GAMs

```{r}
rm(list = ls())
```

```{r}
library(tidyverse)

read_flux <- function(fname) {
  
  #Ensure it reads one file at a time
  if (length(fname) != 1) {
    stop("read_flux() expects a single filename")
  }
  
  df <- read.csv(fname)
  
  #extract site code from file name
  base <- basename(fname)
  no_ext <- gsub("\\.csv$", "", base)
  
 site <- regmatches(
  no_ext,
  regexpr("[A-Z]{2}-[A-Za-z]{2,3}[0-9]?", no_ext)
)
 
 if(length(site) == 0) {
   stop(paste("Could not extract site code from filename:", base))
 }
 
  #add site column
  df$site <- site
  
   # Convert TIMESTAMP_START to datetime and set as index
  df <- df %>%
    mutate(date = ymd_hm(TIMESTAMP_START)) %>%
    select(-TIMESTAMP_START, -TIMESTAMP_END) %>%
    relocate(date)

  df <- df %>%
    mutate(
      year = year(date),
      doy = yday(date),
      hod = hour(date)
    )
  
#renaming some variables
  
   df <- df %>%
    rename(
      GPP = GPP_NT_VUT_REF,
      LE = LE_F_MDS,
      Precip = P_ERA,
      Tair = TA_F_MDS,
      SW_rad = SW_IN_F_MDS,
      Rn = NETRAD,
      Pa = PA_F,
      VPD = VPD_F_MDS,
      Rn = NETRAD
    )

  vars_to_keep <- c("GPP", "Tair", "SW_rad", "Rn", "VPD", "Precip", "Pa", "Rn", "LE")
  df <- df %>% select(date, all_of(vars_to_keep), year, doy, hod, site)
  
  return(df)
  
}
```
```{r}
AU_How <- read_flux("/Users/alicerolfe/year_4_project/fluxnet_project/FLUX/halfhourly/FLX_AU-How_FLUXNET2015_FULLSET_HH_2001-2014_1-4.csv") 

AU_Dap <- read_flux("/Users/alicerolfe/year_4_project/fluxnet_project/FLUX/halfhourly/FLX_AU-DaP_FLUXNET2015_FULLSET_HH_2007-2013_2-4.csv")

AU_Das <- read_flux("/Users/alicerolfe/year_4_project/fluxnet_project/FLUX/halfhourly/FLX_AU-DaS_FLUXNET2015_FULLSET_HH_2008-2014_2-4.csv")

AU_Dry <- read_flux("/Users/alicerolfe/year_4_project/fluxnet_project/FLUX/halfhourly/FLX_AU-Dry_FLUXNET2015_FULLSET_HH_2008-2014_2-4.csv")

AU_Stp <- read_flux("/Users/alicerolfe/year_4_project/fluxnet_project/FLUX/halfhourly/FLX_AU-Stp_FLUXNET2015_FULLSET_HH_2008-2014_1-4.csv")

AU_Asm <- read_flux("/Users/alicerolfe/year_4_project/fluxnet_project/FLUX/halfhourly/FLX_AU-ASM_FLUXNET2015_FULLSET_HH_2010-2014_2-4.csv")
```

```{r}
flux_vars <- c("GPP", "LE", "Tair", "SW_rad", "Rn", "Precip", "Pa")

AU_How <- AU_How %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999)
  )) %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999.9)
  ))

AU_Dap <- AU_Dap %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999)
  )) %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999.9)
  ))

AU_Das <- AU_Das %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999)
  )) %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999.9)
  ))

AU_Dry <- AU_Dry %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999)
  )) %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999.9)
  ))


AU_Stp <- AU_Stp %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999)
  )) %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999.9)
  ))

AU_Asm <- AU_Asm %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999)
  )) %>%
  mutate(across(
    all_of(flux_vars),
    ~na_if(., -9999.9)
  ))
```

```{r}
convert_to_daily <- function(df) {
  
  #Conversion constants
  
  UMOL_TO_MOL <- 1E-6
  MOL_C_TO_GRAMS_C <- 12.0
  SEC_2_HALF_HOUR <- 1800.
  WM2_TO_KG_M2_S <- 1.0 /  ( 2.45 * 1E6)
  PA_2_KPA = 0.001
  HPA_2_KPA = 0.1
  
  df <- df %>%
    mutate(
      GPP = GPP * UMOL_TO_MOL * MOL_C_TO_GRAMS_C * SEC_2_HALF_HOUR,
      ET = LE * WM2_TO_KG_M2_S * SEC_2_HALF_HOUR, 
      VPD = VPD * HPA_2_KPA,
      Precip = Precip * SEC_2_HALF_HOUR
    )
  
  df$date <- ymd_hms(df$date)
  
  #Resample to daily
  
  df <- df %>%
    mutate(date = floor_date(date, "day")) %>%
    group_by(site, date) %>%
    summarise(
      Precip = ifelse(
        sum(!is.na(Precip)) > 0,
        sum(Precip, na.rm = TRUE),
        NA
      ),
      GPP = sum(GPP, na.rm = TRUE),
      ET = sum(ET, na.rm = TRUE), 
      LE = mean(LE, na.rm = TRUE), 
      SW_rad = mean(SW_rad, na.rm = TRUE),
      Tair = mean(Tair, na.rm = TRUE), 
      VPD = mean(VPD, na.rm = TRUE),
      Pa = mean(Pa, na.rm = TRUE),
      Rn = mean(Rn, na.rm = TRUE),
      .groups = "drop"
    )
  
  return(df)
  
}
```

```{r}
How_daily <- convert_to_daily(AU_How)
Dap_daily <- convert_to_daily(AU_Dap)
Das_daily <- convert_to_daily(AU_Das)
Dry_daily <- convert_to_daily(AU_Dry)
Stp_daily <- convert_to_daily(AU_Stp)
Asm_daily <- convert_to_daily(AU_Asm)
```

```{r}
How_daily <- How_daily %>%
  mutate(across(where(is.numeric), ~ ifelse(is.nan(.), NA, .)))

Dap_daily <- Dap_daily %>%
  mutate(across(where(is.numeric), ~ifelse(is.nan(.), NA, .)))

Das_daily <- Das_daily %>%
  mutate(across(where(is.numeric), ~ifelse(is.nan(.), NA, .)))

Dry_daily <- Dry_daily %>%
  mutate(across(where(is.numeric), ~ifelse(is.nan(.), NA, .)))

Stp_daily <- Stp_daily %>%
  mutate(across(where(is.numeric), ~ifelse(is.nan(.), NA, .)))

Asm_daily <- Asm_daily %>%
  mutate(across(where(is.numeric), ~ifelse(is.nan(.), NA, .)))
```

```{r}
How_daily <- How_daily %>%
  drop_na(GPP, VPD, Tair, Precip, Pa, Rn, ET, SW_rad, LE)

Dap_daily <- Dap_daily %>%
  drop_na(GPP, VPD, Tair, Precip, Pa, Rn, ET, SW_rad, LE)

Das_daily <- Das_daily %>%
  drop_na(GPP, VPD, Tair, Precip, Pa, Rn, ET, SW_rad, LE)

Dry_daily <- Dry_daily %>%
  drop_na(GPP, VPD, Tair, Precip, Pa, Rn, ET, SW_rad, LE)

Stp_daily <- Stp_daily %>%
  drop_na(GPP, VPD, Tair, Precip, Pa, Rn, ET, SW_rad, LE)

Asm_daily <- Asm_daily %>%
  drop_na(GPP, VPD, Tair, Precip, Pa, Rn, ET, SW_rad, LE)
```

```{r}
install.packages("ncdf4")
```


Load in Vcmax data:

```{r}
library(terra)
library(ncdf4)

#AU How 
latitude <- -12.4943
longitude <- 131.1523

#
## Vcmax from GOME-2 SIF
#
gome_file <- "/Users/alicerolfe/year_4_project/fluxnet_project/GOME2_VcmaxTg_05deg.tif"

vcmax_gome_raster <- rast(gome_file)
coords <- data.frame(lon = longitude, lat = latitude)
vcmax_gome <- terra::extract(vcmax_gome_raster, coords)
vcmax_gome <- data.frame(lat = latitude, lon = longitude, 
                           Vcmax = vcmax_gome)
vcmax_gome <- vcmax_gome$Vcmax.GOME2_VcmaxTg_05deg

print(vcmax_gome)
```


