---
title: "03_daily_conversion"
output: html_document
date: "2026-02-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

03 - convert half-hourly/hourly data to daily 
1. Convert to daily
2. Convert NaN back to NA

Half-hourly to daily
```{r}
####
##  Convert the 30 min to daily ... someone should add something to check
##. if the data is hourly ...
##
##
##  author: Martin De Kauwe
##  date: 27th February, 2025
##  email: mdekauwe@gmail.com
####
library(tidyverse)

convert_to_daily <- function(df) {

  # Conversion constants
  UMOL_TO_MOL <- 1E-6
  MOL_C_TO_GRAMS_C <- 12.0
  SEC_2_HLFHOUR <- 1800.
  WM2_TO_KG_M2_S <- 1.0 / ( 2.45 * 1E6 )
  PA_2_KPA = 0.001
  HPA_2_KPA = 0.1

  df <- df %>%
    mutate(
      GPP = GPP * UMOL_TO_MOL * MOL_C_TO_GRAMS_C * SEC_2_HLFHOUR,
      ET = Qle * WM2_TO_KG_M2_S * SEC_2_HLFHOUR,
      VPD = VPD * HPA_2_KPA
    )


  # Resample to daily
  df <- df %>%
    mutate(date = floor_date(date, "day")) %>%
    group_by(date) %>%
    summarise(
      GPP = sum(GPP, na.rm=TRUE),
      ET = sum(ET, na.rm=TRUE),
      Precip = sum(Precip, na.rm=TRUE),
      Qle = mean(Qle, na.rm=TRUE),
      Tair = mean(Tair, na.rm=TRUE),
      SW_rad = mean(SW_rad, na.rm=TRUE),
      Rn = mean(Rn, na.rm=TRUE),
      Pa = mean(Pa, na.rm=TRUE),
      VPD = mean(VPD, na.rm=TRUE),
      .groups = "drop"
    )

  return(df)
}
```

Conversion from hourly to daily (e.g., AU-Tum)
```{r}
library(tidyverse)
library(lubridate)

convert_hourly_to_daily <- function(df) {

  # Conversion constants
  UMOL_TO_MOL <- 1E-6
  MOL_C_TO_GRAMS_C <- 12.0
  SEC_2_HOUR <- 3600.
  WM2_TO_KG_M2_S <- 1.0 / (2.45 * 1E6)
  PA_2_KPA <- 0.001
  HPA_2_KPA <- 0.1

  df <- df %>%
    mutate(
      GPP = GPP * UMOL_TO_MOL * MOL_C_TO_GRAMS_C * SEC_2_HOUR,
      ET = Qle * WM2_TO_KG_M2_S * SEC_2_HOUR,
      VPD = VPD * HPA_2_KPA
    )

  # Resample to daily
  df <- df %>%
    mutate(date = floor_date(date, "day")) %>%
    group_by(date) %>%
    summarise(
      GPP = sum(GPP, na.rm = TRUE),
      ET = sum(ET, na.rm = TRUE),
      Precip = sum(Precip, na.rm = TRUE),
      Qle = mean(Qle, na.rm = TRUE),
      Tair = mean(Tair, na.rm = TRUE),
      SW_rad = mean(SW_rad, na.rm = TRUE),
      Rn = mean(Rn, na.rm = TRUE),
      Pa = mean(Pa, na.rm = TRUE),
      VPD = mean(VPD, na.rm = TRUE),
      .groups = "drop"
    )

  return(df)
}

```


NAN back to NA
```{r}
#Convert NaN ('Not a number') back to NA

df_daily <- df_daily %>%
  mutate(across(where(is.numeric), ~ ifelse(is.nan(.), NA, .)))
```

Additional:
- Convert to annual 

```{r}
library(dplyr)
library(lubridate)

convert_to_annual <- function(df_daily) {

  # Add year column
  df_daily <- df_daily %>%
    mutate(year = year(date))

  df_annual <- df_daily %>%
    group_by(year) %>%
    summarise(
      GPP = sum(GPP, na.rm = TRUE),
      ET = sum(ET, na.rm = TRUE),
      Precip = sum(Precip, na.rm = TRUE),
      Qle = mean(Qle, na.rm = TRUE),
      Tair = mean(Tair, na.rm = TRUE),
      SW_rad = mean(SW_rad, na.rm = TRUE),
      Rn = mean(Rn, na.rm = TRUE),
      Pa = mean(Pa, na.rm = TRUE),
      VPD = mean(VPD, na.rm = TRUE),
      .groups = "drop"
    )

  return(df_annual)
}

```

