---
title: "future_envelope_final"
output: html_document
date: "2026-03-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Future envelope final script

1) Background
Tropical (+0.524 kPa), Arid (+0.644 kPa) and Temperate (+0.344 Kpa) increase (Fang et al., 2022)

Biome-specific background increases, accounts for the fact that arid systems will face larger increases in VPD stress than temperate ones.
Make sure site biome assignment is unambiguous
Clearly state you are applying a uniform shift to every daily value in the whole dataset

2) Is GPP more sensitive to increases in frequency of VPD extremes or magnitude of VPD extremes

VPD 90th percentile increase by 28% (Zhou et al., 2019) across all sites 

Targets extremes rather than background

Magnitude vs frequency?

Could increase VPD within each sites 90th percentile by 1.28 (28%) - only apply to values above 90th percentile (Extremes get more intense)
Increase the number of VPD at 90th percentile by 28% (Extreme VPD events become more common)


3) Both background and 90th percentile summer VPD increase

High-end compound stress scenario